services:

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      volumes:
      - ./nginx/html:/usr/share/nginx/html
      depends_on:
        - lumen
      networks:
      - app_network

  lumen:
    build: ./lumen
    container_name: lumen
    ports:
      - 8000:8000
    env_file:
      - path: ./lumen/.env
        required: true
    depends_on:
      - mysql
    volumes:
      - ./lumen:/var/www/html
    networks:
      - app_network
    
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerede
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge