services:
  lumen:
    build: ./lumen
    container_name: lumen
    ports:
      - 8001:8001
    env_file:
      - path: ./lumen/.env
        required: true
    depends_on:
      - mysql
    volumes:
      - ./lumen:/var/www/html
    
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerede
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: